import env from "react-dotenv";

const EMAILJS_SERVICE_ID = env.EMAILJS_SERVICE_ID;
const EMAILJS_TEMPLATE_ID = env.EMAILJS_TEMPLATE_ID;
const EMAILJS_PUBLIC_KEY = env.EMAILJS_PUBLIC_KEY;

export {
    EMAILJS_SERVICE_ID,
    EMAILJS_TEMPLATE_ID,
    EMAILJS_PUBLIC_KEY,
}